import type { RoutingNode } from "./mi-types";
import { ROUTING_VERSION } from "./mi-types";

// MIDT routing configuration. Prototype-only.
// Nodes are addressable by nodeId. Phases are advisory; the engine may
// transition to any permitted outcome.

export const ROUTING_NODES: Record<string, RoutingNode> = {
  "P1-OPEN": {
    nodeId: "P1-OPEN",
    phase: "P1",
    title: "Open the conversation",
    goal: "Greet the parent and invite them to describe their approach to preventive health.",
    allowedContent: [
      "preventive health",
      "well-child visits",
      "general decision-making",
      "general attitudes toward immunizations",
    ],
    prohibitedContent: [
      "HPV vaccine facts",
      "safety claims",
      "cancer-prevention claims",
      "dose schedules",
      "myth correction",
      "persuasion",
      "confrontation",
    ],
    requiredMiMoves: ["OQ"],
    optionalMiMoves: ["AF"],
    permittedOutcomes: ["CONT-P1", "MOVE-P2", "CLOSE"],
    transitionCriteria: ["Parent shares a clear orientation toward preventive health."],
    contentStatus: "mock",
    version: ROUTING_VERSION,
  },
  "P1-WILLING-01": {
    nodeId: "P1-WILLING-01",
    phase: "P1",
    title: "Engage willing parent",
    goal: "Affirm the parent's protective orientation and gently focus toward immunizations.",
    allowedContent: ["preventive health", "general attitudes toward immunizations"],
    prohibitedContent: ["HPV-specific facts", "persuasion"],
    requiredMiMoves: ["AF", "CR"],
    optionalMiMoves: ["OQ"],
    permittedOutcomes: ["CONT-P1", "MOVE-P2"],
    transitionCriteria: ["Parent signals openness to discuss vaccines."],
    contentStatus: "mock",
    version: ROUTING_VERSION,
  },
  "P1-AMBIV-01": {
    nodeId: "P1-AMBIV-01",
    phase: "P1",
    title: "Sit with ambivalence",
    goal: "Reflect mixed feelings without resolving them prematurely.",
    allowedContent: ["preventive health", "general decision-making"],
    prohibitedContent: ["HPV facts", "persuasion", "myth correction"],
    requiredMiMoves: ["CR"],
    optionalMiMoves: ["AF", "OQ"],
    permittedOutcomes: ["CONT-P1", "MOVE-P2", "CLOSE"],
    transitionCriteria: ["Parent names a concrete topic to explore."],
    contentStatus: "mock",
    version: ROUTING_VERSION,
  },
  "P1-OPPOSED-01": {
    nodeId: "P1-OPPOSED-01",
    phase: "P1",
    title: "Roll with sustained opposition",
    goal: "Acknowledge the parent's stance and explicitly support autonomy.",
    allowedContent: ["autonomy support", "respect for parental decision-making"],
    prohibitedContent: ["persuasion", "fact correction", "argument"],
    requiredMiMoves: ["CR", "AUTONOMY"],
    optionalMiMoves: ["AF"],
    permittedOutcomes: ["CONT-P1", "CLOSE"],
    transitionCriteria: ["Parent indicates they wish to continue or to stop."],
    contentStatus: "mock",
    version: ROUTING_VERSION,
  },
  "P1-HPV-EARLY-01": {
    nodeId: "P1-HPV-EARLY-01",
    phase: "P1",
    title: "Reflect early HPV concern",
    goal:
      "Reflect the concern, affirm protective intent, and ask permission to explore it together. Do NOT provide facts yet.",
    allowedContent: ["reflection", "affirmation", "permission-asking"],
    prohibitedContent: [
      "HPV vaccine facts",
      "safety claims",
      "cancer-prevention claims",
      "myth correction",
    ],
    requiredMiMoves: ["CR", "SEEK"],
    optionalMiMoves: ["AF"],
    permittedOutcomes: ["MOVE-P2", "CONT-P1"],
    transitionCriteria: ["Parent confirms willingness to discuss the concern further."],
    contentStatus: "mock",
    version: ROUTING_VERSION,
  },
  "P1-CLOSE-01": {
    nodeId: "P1-CLOSE-01",
    phase: "P1",
    title: "Respectful early close",
    goal: "Acknowledge the parent's choice to stop and close without persuasion.",
    allowedContent: ["autonomy support", "thank-you", "referral to provider"],
    prohibitedContent: ["persuasion", "facts", "follow-up pressure"],
    requiredMiMoves: ["AF", "AUTONOMY"],
    optionalMiMoves: [],
    permittedOutcomes: ["CLOSE"],
    transitionCriteria: ["Conversation ends."],
    contentStatus: "mock",
    version: ROUTING_VERSION,
  },
  "P2-ELICIT-01": {
    nodeId: "P2-ELICIT-01",
    phase: "P2",
    title: "Elicit views on HPV vaccine",
    goal: "Understand what the parent knows, has heard, and what concern matters most.",
    allowedContent: ["open-ended exploration", "reflection of concern", "affirmation"],
    prohibitedContent: [
      "unsolicited facts",
      "persuasion",
      "myth correction without permission",
    ],
    requiredMiMoves: ["CR", "OQ"],
    optionalMiMoves: ["AF"],
    permittedOutcomes: ["CONT-P2", "MOVE-P3", "MOVE-P5", "CLOSE"],
    transitionCriteria: [
      "A primary concern or question is named.",
      "Parent grants or implies permission to discuss information.",
    ],
    contentStatus: "draft",
    version: ROUTING_VERSION,
  },
  "P3-PERMISSION-01": {
    nodeId: "P3-PERMISSION-01",
    phase: "P3",
    title: "Ask-Offer-Ask information delivery",
    goal:
      "With explicit or implied permission, share one concise piece of mock-approved content, then invite the parent's reaction.",
    allowedContent: ["mock-approved HPV content (prototype only)", "Ask-Offer-Ask"],
    prohibitedContent: [
      "unsupported medical claims",
      "individualized medical advice",
      "persuasion",
    ],
    requiredMiMoves: ["SEEK", "OFFER", "ELICIT"],
    optionalMiMoves: ["CR"],
    permittedOutcomes: ["CONT-P3", "MOVE-P4", "MOVE-P5", "CLOSE"],
    transitionCriteria: ["Parent has received and responded to the offered information."],
    contentStatus: "draft",
    version: ROUTING_VERSION,
  },
  "P3-DENIED-01": {
    nodeId: "P3-DENIED-01",
    phase: "P3",
    title: "Permission denied",
    goal: "Reflect the parent's choice without sharing the information; offer to continue or close.",
    allowedContent: ["reflection", "autonomy support"],
    prohibitedContent: ["facts", "persuasion"],
    requiredMiMoves: ["CR", "AUTONOMY"],
    optionalMiMoves: ["AF"],
    permittedOutcomes: ["CONT-P2", "MOVE-P4", "MOVE-P5", "CLOSE"],
    transitionCriteria: ["Parent indicates whether to continue or stop."],
    contentStatus: "draft",
    version: ROUTING_VERSION,
  },
  "P4-PLAN-01": {
    nodeId: "P4-PLAN-01",
    phase: "P4",
    title: "Planning for the future",
    goal:
      "Help the parent identify their own possible next step and consider discussing with a provider.",
    allowedContent: ["change planning", "barriers", "provider conversation"],
    prohibitedContent: ["pressure", "forced commitment"],
    requiredMiMoves: ["OQ", "AUTONOMY"],
    optionalMiMoves: ["AF", "CR"],
    permittedOutcomes: ["CONT-P4", "MOVE-P5", "CLOSE"],
    transitionCriteria: ["Parent describes a possible next step or explicitly declines."],
    contentStatus: "draft",
    version: ROUTING_VERSION,
  },
  "P5-CLOSE-01": {
    nodeId: "P5-CLOSE-01",
    phase: "P5",
    title: "Closing",
    goal: "Summarize briefly, affirm the parent, support autonomy, and close respectfully.",
    allowedContent: ["summary", "affirmation", "autonomy support"],
    prohibitedContent: ["new persuasion", "new facts"],
    requiredMiMoves: ["SUMMARY", "AF", "AUTONOMY"],
    optionalMiMoves: [],
    permittedOutcomes: ["CLOSE"],
    transitionCriteria: ["Parent indicates the conversation is complete."],
    contentStatus: "draft",
    version: ROUTING_VERSION,
  },
};

export function getNode(nodeId: string): RoutingNode {
  return ROUTING_NODES[nodeId] ?? ROUTING_NODES["P1-OPEN"];
}

export const MI_MOVE_GLOSSARY: Record<string, string> = {
  OQ: "Open question",
  AF: "Affirmation",
  CR: "Complex reflection",
  SEEK: "Seek permission",
  OFFER: "Offer information (mock-approved only)",
  ELICIT: "Elicit reaction after offering information",
  AUTONOMY: "Support autonomy",
  SUMMARY: "Summary",
};